### ISSUE TITLE
Incorrect type. Expected array - for valid Yaml

### ISSUE THREAD

**Issue by guw** [de-jcup/eclipse-yaml-editor#101]
I started playing with Antora. It requires defining the following yaml:
```
# $(npm bin)/antora --clean --fetch antora-playbook.yml
site:
  title: My Documentation
  url: https://www.mycooldocs.com/
  start_page: home::index.adoc

# see https://docs.antora.org/antora/2.3/playbook/configure-runtime/
runtime:
  cache_dir: ./.cache/antora
output:
  dir: ./public

content:
  sources:
  - url: .
    branches: HEAD
    start_path: home

ui:
  bundle:
    url: ./ui/build/ui-bundle.zip
    snapshot: true
```

Opening the Yaml underlines everything read with the error:
> Incorrect type. Expected "array".

I tried two online Yaml validators and they all agree - this is valid Yaml.
