### ISSUE TITLE
Comments starting at beginning of line break folding

### ISSUE THREAD

**Issue by alexmarinn** [de-jcup/eclipse-yaml-editor#109]
```yaml
items:
    - part_no:   A4786
      descrip:   Water Bucket (Filled)
# This comment breaks folding - folding starts on this line instead of the "items" line above
      price:     1.47
      quantity:  4
````
