### ISSUE TITLE
Ability to remove trailing whitespace

### ISSUE THREAD

**Issue by pwatt01** [de-jcup/eclipse-yaml-editor#112]
It would very very useful if we coudl please have an option in the formator preferences to remove trailing whitespace on save.

**Comment by de-jcup** [comment]
Hello @pwatt01 ,

please add some sample code example with "before" and "after" save action so it is clear what is meant.

Currently the formatting is done by snake yaml parser. Only comment restoring is done additionally by the plugin (because the parser does not provide this).
It could be possible to implement an addition here, but I have not much time at the moment and so it must be very clear what you want before I (or anybody else) can implement the feature.

**Comment by pwatt01** [comment]
Thanks for replying. It is kind of hard to show this as the review removes the whitespace automatically, so i have added an image on pasteboard to desccribe what I am after. If not, the below might make sense

https://pasteboard.co/U5usx7PfKR89.png
Before:          

```yaml
doe: "a deer, a female deer"\s\s\s\s\t\s\s\t\t\t\
ray: "a drop of golden sun"\s\s\s\s\
pi: 3.14159\s\s\s\s\
xmas: true\t
french-hens: 3\s\s
calling-birds:\s\s\s\s\s\s\t\t\t\t\t\s\s\s\s\t\t\t
 - huey\t\t\t\t\t
 - dewe\s\s\s\s\\t\t\t\t\t\t
```
After
```yaml   
doe: "a deer, a female deer"
ray: "a drop of golden sun"
pi: 3.14159
xmas: true
french-hens: 3
calling-birds:
 - huey
 - deweyy
 ```
