### ISSUE TITLE
What does mean: mapping values are not allowed here in 'reader'

### ISSUE THREAD

**Issue by mxmlnglt** [de-jcup/eclipse-yaml-editor#64]
I have this yml file:
> logging:
>   level:
>     graphql: debug
>       execution:
>         ExecutionStrategy: info

Validation message says:
> mapping values are not allowed here
>  in 'reader', line 4, column 16:
>           execution:
>                    ^

What does that mean? Especially what is **'reader'** refering to?

![Yaml_editor_validation_message_reader](https://user-images.githubusercontent.com/29626929/58011663-41675780-7ae2-11e9-971d-dfc1666e7c77.png)

**Comment by de-jcup** [comment]
Hello @mxmlnglt,

Parent nodes may not have direct values in YAML.

Your `graphql: debug` cannot be a parent node.

so this is not correct:
```
logging:
  level:
    graphql: debug
      execution:
        ExecutionStrategy: info
```
but this one is correct (at least correct Yaml, I do not know the log level format)
```
logging:
  level:
    graphql: debug
    execution:
        ExecutionStrategy: info
```
