### ISSUE TITLE
(minor) asterisk character break syntax highlighting

### ISSUE THREAD

**Issue by arboriginal** [de-jcup/eclipse-yaml-editor#69]
If you use an asterisk character in a named value, the entire row stays white.

Example:
```Yaml
something:
  something.with.asterisk.*: # this line will not be colorized
    - value1
    - value2
```
