### ISSUE TITLE
Editor linking with outline does not work with inner elements

### ISSUE THREAD

**Issue by de-jcup** [de-jcup/eclipse-yaml-editor#73]
```yaml
# Just a simple example

apiVersion: v1
kind: Pod
metadata:
  name: busybox-sleep
 
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - sleep
    - "1000000"

```
when selecting name: busyboxsleep

neither by key or value the outline element is not selected.
