### ISSUE TITLE
Full line go template gives an error

### ISSUE THREAD

**Issue by bentatham** [de-jcup/eclipse-yaml-editor#79]
First off - amazing that you added support for Go Templates for Helm in #76 .

If I have a template where the entire file is in a conditional like this:

```
{{ if and .Values.apollo (eq .Values.apollo "true") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo
  labels:
    app: apollo
spec:
 ...
{{ end }}
```

I get an error from the yaml editor:

```
mapping values are not allowed here
 in 'reader', line 2, column 11:
    apiVersion: apps/v1
              ^
```

Not sure if it works in all cases, but maybe try to treat all lines that start with `{{` as comments? Or some other hack of the yaml like that?
