### ISSUE TITLE
dictionary key is converted to boolean value by formatter

### ISSUE THREAD

**Issue by klei1984** [de-jcup/eclipse-yaml-editor#85]
I am setting up a github actions script which is in yaml format. Actions has a specific keyword set which relies on `<key>: <value>` syntax. See this [page](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#on) for all the keywords.

The on.push.branches event is basically described with the below yaml code:

```
name: GitHub CI

on:
  push:
    branches:
    - master
    tags: [ '**' ]
```

I am using version 1.6.1 of the editor which converts the `on:` key to the boolean `true` value as in the below result:

```
name: GitHub CI
true:
  push:
    branches:
    - master
    tags:
    - '**'
```

I did not check what github actions actually do with such a script, but my assumption is that keys are not supposed to be replaced by boolean values.

Am I missing something? I found a similar issue [here](https://github.com/go-yaml/yaml/issues/214) but that is another tool and another context.

Or could it be that the yaml format used by Github is not actually compliant to either version of the standard and thus I should not try to use a yaml editor for such scripts?
