### ISSUE TITLE
Expecting a 'String' but got a 'Mapping' node

### ISSUE THREAD

**Issue by sgullapalli13** [de-jcup/eclipse-yaml-editor#92]
Similar to https://stackoverflow.com/questions/62304206/eclipse-yaml-error-expected-a-string-but-got-a-mapping-node

I'm sort of new to all this but in our application.yml file we have a block similar to

```
#New Section
security:
  token: ABCDEFG123456789
  tokenExpiration: 6000000
```

that has the error in the title. I've opened it with both the yaml editor and without and these lines keep throwing an error, but when I close the file, the error disappears (in eclipses problems section etc). I don't want this to come back later to bite me, so is this a parser error or something else?
